#          _   _                 _               _              _   _
#         /\_\/\_\ _           /\ \             /\ \           /\_\/\_\ _
#        / / / / //\_\        /  \ \           /  \ \         / / / / //\_\
#       /\ \/ \ \/ / /       / /\ \ \         / /\ \ \       /\ \/ \ \/ / /
#      /  \____\__/ /       / / /\ \ \       / / /\ \_\     /  \____\__/ /
#     / /\/________/       / / /  \ \_\     / / /_/ / /    / /\/________/
#    / / /\/_// / /       / / /    \/_/    / / /__\/ /    / / /\/_// / /
#   / / /    / / /       / / /            / / /_____/    / / /    / / /
#  / / /    / / /       / / /________    / / /          / / /    / / /
#  \/_/    / / /       / / /_________\  / / /           \/_/    / / /
#          \/_/        \/____________/  \/_/                    \/_/


# Minecraft Package Manager (MCPM) by Arman Studios

# Configuration file
# feel free to change config settings based on your needs.

# Default Language for translations.
# Default: 'en_US'
# Note: be sure the specified language is available on lang folder in Installation/Project directory.
language: 'en_US'