name: mcpm Executable file Build
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm i

      - name: Bundle
        run: npx esbuild src/main.ts --bundle --platform=node --format=cjs --outfile=dist/bundled/main.js --loader:.ts=ts

      - name: Build
        run: npm run compile

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: |
            build/generated/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}